User.create!(first_name: "Hyun", username: "hcho774", password_digest: BCrypt::Password.create("123"), dob_day: "10", dob_month:"12", dob_year: "1991", show_gender: false, gender_identity: "man", gender_interest:"woman",img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: "Amy", username: "amy", password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.male_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "man", gender_interest: "woman", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)
# User.create!(first_name: Faker::Name.unique.name, username: Faker::Name.unique.female_first_name, password_digest: BCrypt::Password.create("123"), dob_day: "6", dob_month:"2",dob_year: "1991",show_gender: false,  gender_identity: "woman", gender_interest: "man", img:Faker::Avatar.image, matches: 0)


Question.create!(questions: "Would you prefer to live alone?")

# Answer.create!(user_id: 1, question_id: 1, answer: true, pitch: Faker::Quote.unique.famous_last_words)
# Answer.create!(user_id: 2, question_id: 1, answer: false, pitch: Faker::Quote.unique.famous_last_words)
# Answer.create!(user_id: 3, question_id: 1, answer: true, pitch: Faker::Quote.unique.famous_last_words )
# Answer.create!(user_id: 4, question_id: 1, answer: false, pitch: Faker::Quote.unique.famous_last_words )
# Answer.create!(user_id: 5, question_id: 1, answer: true, pitch: Faker::Quote.unique.famous_last_words )
# Answer.create!(user_id: 6, question_id: 1, answer: true, pitch: Faker::Quote.unique.famous_last_words )
# Answer.create!(user_id: 7, question_id: 1, answer: false, pitch: Faker::Quote.unique.famous_last_words )
# Answer.create!(user_id: 8, question_id: 1, answer: false, pitch: Faker::Quote.unique.famous_last_words )
# Answer.create!(user_id: 9, question_id: 1, answer: false, pitch: Faker::Quote.unique.famous_last_words )
# Answer.create!(user_id: 10, question_id: 1, answer: true, pitch: Faker::Quote.unique.jack_handey)
# Answer.create!(user_id: 11, question_id: 1, answer: false, pitch: Faker::Quote.unique.jack_handey )
# Answer.create!(user_id: 12, question_id: 1, answer: true, pitch: Faker::Quote.unique.jack_handey)
# Answer.create!(user_id: 13, question_id: 1, answer: false, pitch: Faker::Quote.unique.jack_handey)
# Answer.create!(user_id: 14, question_id: 1, answer: true, pitch: Faker::Quote.unique.jack_handey)
# Answer.create!(user_id: 15, question_id: 1, answer: false, pitch: Faker::Quote.unique.jack_handey)
# Answer.create!(user_id: 16, question_id: 1, answer: false, pitch: Faker::Quote.unique.jack_handey)
# Answer.create!(user_id: 17, question_id: 1, answer: true, pitch: Faker::Quote.unique.jack_handey)
# Answer.create!(user_id: 18, question_id: 1, answer: true, pitch: Faker::Quote.unique.jack_handey)
# Answer.create!(user_id: 19, question_id: 1, answer: true, pitch: Faker::Quotes::Shakespeare.unique.hamlet_quote )
# Answer.create!(user_id: 19, question_id: 1, answer: true, pitch: Faker::Quotes::Shakespeare.unique.hamlet_quote )
# Answer.create!(user_id: 20, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.hamlet_quote )
# Answer.create!(user_id: 21, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.hamlet_quote )
# Answer.create!(user_id: 22, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.hamlet_quote )
# Answer.create!(user_id: 23, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.hamlet_quote )
# Answer.create!(user_id: 24, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.hamlet_quote )
# Answer.create!(user_id: 25, question_id: 1, answer: true, pitch: Faker::Quotes::Shakespeare.unique.hamlet_quote )
# Answer.create!(user_id: 26, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.hamlet_quote )
# Answer.create!(user_id: 27, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.hamlet_quote )
# Answer.create!(user_id: 28, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.king_richard_iii_quote  )
# Answer.create!(user_id: 29, question_id: 1, answer: true, pitch: Faker::Quotes::Shakespeare.unique.king_richard_iii_quote  )
# Answer.create!(user_id: 30, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.king_richard_iii_quote  )
# Answer.create!(user_id: 31, question_id: 1, answer: true, pitch: Faker::Quotes::Shakespeare.unique.king_richard_iii_quote  )
# Answer.create!(user_id: 32, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.king_richard_iii_quote  )
# Answer.create!(user_id: 33, question_id: 1, answer: true, pitch: Faker::Quotes::Shakespeare.unique.king_richard_iii_quote  )
# Answer.create!(user_id: 34, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.king_richard_iii_quote  )
# Answer.create!(user_id: 35, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.king_richard_iii_quote  )
# Answer.create!(user_id: 36, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.hamlet_quote   )
# Answer.create!(user_id: 37, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.hamlet_quote  )
# Answer.create!(user_id: 38, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.hamlet_quote )
# Answer.create!(user_id: 39, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.hamlet_quote )
# Answer.create!(user_id: 40, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.hamlet_quote )
# Answer.create!(user_id: 41, question_id: 1, answer: false, pitch: Faker::Quotes::Shakespeare.unique.as_you_like_it_quote)





puts "seeding done"

# This file should contain all the regitcord creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
